name: cpp-hpc-binder
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.15.0
  - cling
  - matplotlib
  - jupyterlab
  - notebook
  - cppzmq
  - xtl
  - xtensor
  - xtensor-blas
  - cmake
  - make
  - gcc_linux-64
  - gxx_linux-64
  - pip
  - pip:
      - jupyterlab_code_formatter